spring:
  application:
    name: archive.app

  datasource:
    url: jdbc:postgresql://localhost:5432/<DB_NAME>
    username: <DB_USERNAME>
    password: <DB_PASSWORD>

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  thymeleaf:
    cache: false

logging:
  level:
    it.personal: INFO
